FROM python:3

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY tests ./tests
COPY bluetti_bt_lib ./bluetti_bt_lib

RUN python3 -m unittest discover -s tests -p "*.py"
RUN python3 -m unittest discover -s tests/fields -p "*.py"
RUN python3 -m unittest discover -s tests/registers -p "*.py"
RUN python3 -m unittest discover -s tests/base_devices -p "*.py"
RUN python3 -m unittest discover -s tests/devices -p "*.py"
